"""Generate the paper's tables and vector figure from the extracted evidence.

Requires reportlab only for the figure, not the MRA runtime. This script performs
no training and never changes source evidence. --check compares generated bytes.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "academic" / "paper"
DATA = PAPER / "experimental-data.json"


def esc(value):
    value = str(value)
    for a, b in (("×", "x"), ("σ", "sigma"), ("∞", "infinity"), ("—", "--"), ("–", "--")):
        value = value.replace(a, b)
    return "".join({"&": r"\&", "%": r"\%", "_": r"\_", "#": r"\#", "$": r"\$"}.get(c, c) for c in value)


def num(value, digits=4):
    return f"{value:.{digits}f}"


def table(caption, label, headers, rows, wide=True, note=""):
    env = "table*" if wide else "table"
    spec = "l" + "r" * (len(headers) - 1)
    lines = [rf"\begin{{{env}}}[t]", r"\centering\small", rf"\caption{{{caption}}}", rf"\label{{{label}}}",
             rf"\begin{{tabular}}{{{spec}}}", r"\toprule", " & ".join(headers) + r" \\", r"\midrule"]
    lines += [" & ".join(esc(v) for v in row) + r" \\" for row in rows]
    lines += [r"\bottomrule", r"\end{tabular}"]
    if note:
        width = r"\textwidth" if wide else r"\columnwidth"
        lines += [r"\par\smallskip", rf"\begin{{minipage}}{{{width}}}\small {note}\end{{minipage}}"]
    return "\n".join(lines + [rf"\end{{{env}}}"])


def build_tex(data):
    tables = {t["id"]: t for t in data["tables"]}
    def rows(key):
        return [r["values"] for r in tables[key]["rows"]]
    macros = []
    def macro(name, content):
        macros.append("\\newcommand{\\" + name + "}{%\n" + content + "\n}\n")
    controlled = [v for v in rows("controlled_groups") if v["tier_role"] == "primary"]
    controlled.sort(key=lambda v: v["true_exact_risk"]["numerator"] / v["true_exact_risk"]["denominator"])
    assert len(controlled) == 3
    cr = [[v["risk_role"], num(v["true_exact_risk"]["numerator"] / v["true_exact_risk"]["denominator"], 2),
           num(v["mean_floor"]), num(v["mean_ceiling"]), v["decision_power"]["expected_decision"],
           str(v["decision_power"]["count"]) + "/" + str(v["replicates"])] for v in controlled]
    macro("ControlledTable", table("Controlled primary finite channels; $n=2{,}000$ per state. Model-family names are synthetic labels.", "tab:controlled",
        ["Role", "$R^*$", "Mean $L$", "Mean $U$", "Decision", "Correct"], cr,
        note="All primary cells observed zero upper undercoverage; per-cell simultaneous upper 0.015606. HOLD at the exact threshold is expected."))
    names = {"cnn": "CNN", "xgboost": "XGBoost", "compact_transformer_llm_proxy": "Transformer proxy"}
    mr = []
    for version in (2, 3):
        repeat = {(v["collector_model"], v["variant_id"]): v for v in rows(f"model_v{version}_repeated_summary")}
        for v in rows(f"model_v{version}_primary"):
            q = repeat[(v["collector_model"], v["variant_id"])]
            clear = q["clear_count"]
            dc = q.get("decision_counts", {"CLEAR": clear, "HOLD": q["replicates"] - clear, "BLOCK": 0})
            mr.append([f"v{version} " + names[v["collector_model"]], "raw" if v["variant_id"] == "raw_bins" else "erased",
                num(v["oracle_exact_bayes_risk_decimal"]), num(v["production_interval"]["floor"]), num(v["production_interval"]["ceiling"]),
                f"{dc['CLEAR']}/{dc['HOLD']}/{dc['BLOCK']}"])
    macro("ModelCeilingTable", table("All primary model-backed intervals and repeated decisions (C/H/B). The v2 and v3 hypotheses differ.", "tab:model-ceilings",
        ["Version / model", "Wrapper", "$R^*$", "$L$", "$U$", "C/H/B"], mr,
        note=r"Each row has 200 repeated analyzer trials. V2 raw-proxy CLEAR lower bound 0.449431 failed its target. V3 resolution applies only at margin $\geq0.10$; no oracle risk exceeds 0.65."))
    public = []
    for v in rows("tree_primary"):
        p = v["privacy"]
        public.append(["XGB " + str(v["case"]["rounds"]) + "r", f"{v['training_rows']:,}", num(v["training_wall_seconds"], 2),
            num(p["elapsed_seconds"], 3), num(v["training_sampled_peak_working_set_bytes"] / 2**20, 1) + " M host",
            num(100 * v["holdout_accuracy"], 2) + "% acc", num(p["simultaneous_lower_bound"]), num(1 - p["simultaneous_lower_bound"])])
    for v in rows("vision_scaling"):
        p = v["membership_screen"]
        public.append([v["architecture"], f"{v['train_rows']:,}", num(v["train_seconds"], 2), num(p["audit_seconds"], 2),
            num(v["training_peak_gpu_bytes"]["allocated"] / 2**30, 2) + " G GPU", num(v["test_accuracy"] * 100, 2) + "% acc", num(p["floor"]), num(p["gap"])])
    for v in rows("llm_scaling"):
        p = v["privacy"]
        scoring = sum(val for key, val in v["scoring_seconds_by_cohort"].items() if key != "utility")
        public.append(["GPT-2" if v["model"] == "gpt2" else "Qwen-0.5B", f"{v['training']['rows']:,}", num(v["training"]["seconds"], 2),
            num(scoring, 2), num(v["training"]["peak_allocated_bytes"] / 2**30, 2) + " G GPU", num(v["utility_after"]["token_weighted_nll"]) + " NLL", num(p["floor"]), num(p["gap"])])
    assert len(public) == 17
    macro("PublicWorkloadTable", table("All 17 local primary workload cells (historical source version). Raw attack floors are not adjusted to the trivial guessing strategy.", "tab:public-workloads",
        ["Model", "Train rows", "Train s", "Privacy s", "Peak memory", "Utility after", "Raw $L$", "$1-L$"], public,
        note="Every ceiling is one. Host M denotes MiB working set; GPU G denotes GiB allocated. Tasks, instrumentation and utility metrics differ. Primary tree times overlap preparation; use isolated repeats for timing comparisons."))
    memory = {v["profile"]["profile_id"]: v["maximum_stage_peak_working_set_mib"] for v in rows("cli_interpreter_memory")}
    labels = {"baseline": "Baseline", "candidates-8": "8 candidates", "candidates-32": "32 candidates", "threats-16": "16 threat records", "threats-64": "64 threat records", "artifact_mib-16": "16 MiB artifact", "artifact_mib-512": "512 MiB artifact", "prefix_runs-32": "68 audit events", "prefix_runs-128": "260 audit events", "monitoring_events-64": "72 transcript events", "monitoring_events-256": "264 transcript events"}
    br = []
    for v in rows("cli_timing_profiles"):
        key, s = v["profile"]["profile_id"], v["chain_seconds"]
        br.append([labels[key], num(s["median"], 3), num(s["minimum"], 3) + "--" + num(s["maximum"], 3), num(memory[key], 2) if key in memory else "not measured"])
    macro("ProtocolTimingTable", table("Historical nine-command CLI chains: three timing repeats per profile. Corrected interpreter-memory supplement is separate, $n=1$ for six profiles.", "tab:protocol-timing",
        ["One-axis profile", "Median s", "Min--max s", "Interpreter MiB"], br,
        note="Synthetic linkage/governance fixtures; no training or live registry/gateway. Invalid launcher-memory readings are excluded here and retained separately in the companion data."))
    supplement = []
    diag = [v for v in rows("controlled_groups") if v["tier_role"] != "primary"]
    supplement.append(table("All controlled diagnostic cells (not additional primary evidence).", "tab:diagnostics",
        ["Role", "$n$/state", "Repeats", "Mean $L$", "Mean $U$", "Width", "C/H/B"],
        [[v["risk_role"], v["sample_size_per_state"], v["replicates"], num(v["mean_floor"]), num(v["mean_ceiling"]), num(v["mean_interval_width"]),
          "/".join(str(v["decision_counts"][k]) for k in ("CLEAR", "HOLD", "BLOCK"))] for v in diag]))
    tight = []
    for version in (2, 3):
        for v in rows(f"model_v{version}_repeated_summary"):
            tight.append([f"v{version} " + names[v["collector_model"]], "raw" if v["variant_id"] == "raw_bins" else "erased", num(v["mean_ceiling"]),
                num(v["mean_interval_width"]), num(v["mean_ceiling_excess_over_oracle"]), num(v["p95_ceiling_excess_over_oracle"])])
    supplement.append(table("Repeated ceiling tightness: all v2/v3 families. Tightness is not a substitute for coverage.", "tab:tightness",
        ["Model", "Wrapper", "Mean $U$", "Mean width", "Mean $U-R^*$", "P95 $U-R^*$"], tight))
    supplement.append(table("All nine isolated tree timing repetitions. These are identical seeded computations, not independent training replications.", "tab:tree-repeats",
        ["Train rows", "Repeat", "Train s", "Privacy s", "Host peak MiB"],
        [[f"{v['training_rows']:,}", v["replicate"], num(v["training_wall_seconds"], 3), num(v["privacy"]["elapsed_seconds"], 3), num(v["training_sampled_peak_working_set_bytes"] / 2**20, 2)] for v in rows("tree_timing_repeats")]))
    supplement.append(table("LLM utility, throughput and adverse membership evidence for all six local cells.", "tab:llm-utility",
        ["Model", "Rows", "NLL before", "NLL after", "Input tokens/s", "Raw $L$", "Derived advantage floor"],
        [["GPT-2" if v["model"] == "gpt2" else "Qwen-0.5B", f"{v['training']['rows']:,}", num(v["utility_before"]["token_weighted_nll"]), num(v["utility_after"]["token_weighted_nll"]),
          num(v["training"]["input_tokens_per_second"], 0), num(v["privacy"]["floor"]), num(max(0, 2 * v["privacy"]["floor"] - 1))] for v in rows("llm_scaling")]))
    hook = rows("hook_audit_table_03")
    supplement.append(table("Historical L4 language hook matrix: published rounded observations, one run per model, 512 steps each.", "tab:llm-hooks",
        ["Model", "Parameters", "NLL/PPL before", "NLL/PPL after", "Rows/s", "GPU GiB"],
        [[v["Model and frozen revision"].split(" `")[0], v["Parameters"], v["Holdout NLL / PPL before"], v["Holdout NLL / PPL after"], v["Rows/s"], v["Peak GPU GiB"]] for v in hook]))
    supplement.append(table("Historical L4 vision hook matrix: published rounded observations, one epoch and 169 steps each.", "tab:vision-hooks",
        ["Model", "Parameters", "CE before/after", "Accuracy before/after", "Images/s", "GPU GiB"],
        [[v["Model"], v["Parameters"], v["Test CE before"] + "/" + v["Test CE after"], v["Accuracy before"] + "/" + v["Accuracy after"], v["Train images/s"], v["Peak GPU GiB"]] for v in rows("hook_audit_table_07")]))
    supplement.append(table("All 12 measured historical LLM context screens. K0: prior; K1: metadata; K2: candidate loss; K3: metadata and loss. Published rounded values.", "tab:contexts",
        ["Model", "Profile", "Before BA/AUC", "After BA/AUC"],
        [[v["Model"], v["Knowledge profile"].split()[0], v["Before BA / AUC"], v["After BA / AUC"]] for v in rows("hook_audit_table_04") if v["Model"] != "All"],
        note="K2/K3 require candidate-scoring access, not merely generation. K4 is a separate exact-roster disclosure condition, not a numerical screen. These workers cannot clear or block an MRAP release."))
    supplement.append(table("All eight historical vision perturbation cells on 512 images; published rounded values, not robustness guarantees.", "tab:perturbations",
        ["Model", "Condition", "CE", "Accuracy", "Acc. drop", "Attack success", r"$L_\infty$"],
        [[v["Model"], v["Condition"].replace("untargeted true-label ", ""), v["Cross-entropy"], v["Accuracy"], v["Accuracy drop from clean"], v["Attack success on clean-correct"], v["Measured pixel L∞"]] for v in rows("hook_audit_table_08")],
        note="Attack success is conditional on clean-correct examples. Brightness/noise and FGSM are different perturbations; their scores cannot be pooled into privacy risk."))
    legacy = []
    for version in (0, 1):
        for v in rows(f"legacy_privacy_{version}"):
            legacy.append(["legacy " + str(version), v["model"], v["training_rows"], num(v["utility_accuracy"]), v["attack/member_trials"], v["attack/nonmember_trials"], num(v["attack/equal_prior_success"])])
    supplement.append(table("Unsealed legacy public-privacy outputs: descriptive point values only. Their pooled binomial lower bounds are not endorsed.", "tab:legacy",
        ["Report", "Model", "Train rows", "Accuracy", "Member $n$", "Nonmember $n$", "Success"], legacy,
        note="No verified simultaneous family or completed publication bundle. Unequal group success probabilities need not yield a single binomial count; reported confidence fields remain labelled as unsupported in the companion JSON."))
    strategic = []
    for key in ("strategic_smoke", "strategic_full"):
        for i, v in enumerate(rows(key), 1):
            a, b = v["sampled_minimum_margin"], v["sampled_maximum_margin"]
            strategic.append(["smoke" if key.endswith("smoke") else "full", i, v["certified_status"], v["sampled_parameter_tuples"], v["tuples_meeting_strict_margin"], num(a["numerator"] / a["denominator"], 3), num(b["numerator"] / b["denominator"], 3)])
    supplement.append(table("Synthetic strategic samples: all five registered sample-claim rows in each local report. No behavioral validation.", "tab:strategic",
        ["Report", "Claim row", "Status", "Tuples", "Strict-margin tuples", "Min margin", "Max margin"], strategic,
        note="Exact claim IDs and synthetic parameter contracts remain in the companion data. Sampled consistency is not proof of institutional compliance, deterrence, or deployment readiness."))
    macro("SupplementaryTables", "\n".join(supplement).replace(r"\caption{", r"\caption{Appendix: "))
    return ("% Generated from academic/paper/experimental-data.json; do not hand-edit numeric cells.\n" + "\n".join(macros)).encode()


def build_gap_tex(report):
    studies = {study["id"].split("_")[0]: study for study in report["studies"]}
    selected = studies["G2"]["construction"]
    from fractions import Fraction
    probabilities = [float(Fraction(row["selected_false_release_probability"])) for row in selected]
    descriptions = {
        "G1": ("Decoder cells", "Same blind success 1/2; exhaustive optima 1/2 and 1."),
        "G2": ("Exact probability bins", f"Selected false release {probabilities[0]:.6f}; allocated control {probabilities[1]:.6f}."),
        "G3": ("Declared subsets", "Only the complete subset passes; hidden-world views remain identical."),
        "G4": ("Decoder cells", "Identical marginals; joint optima 1/2 (noise) and 1 (XOR)."),
        "G5": ("Channel-pair parameters", "Four sharp TV penalties; four rare-disclosure posteriors equal 1."),
        "G6": ("Reducer inputs", "93,312 grid inputs + 10 boundaries; no declarative disagreements."),
        "G7": ("Semantic worlds", "Both accounts authentic; full-channel admission rejects the false ceiling."),
    }
    lines = [r"% Generated from academic/paper/gap-construction-results.json.", r"\newcommand{\GapConstructionTable}{%",
             r"\begin{table*}[t]", r"\centering\small",
             r"\caption{Exact finite gap constructions and repair controls. Counts have different units; no pooled success rate is meaningful.}",
             r"\label{tab:gap-constructions}",
             r"\begin{tabular}{lr>{\raggedright\arraybackslash}p{0.22\textwidth}>{\raggedright\arraybackslash}p{0.57\textwidth}}",
             r"\toprule", r"Gap & Count & Unit & Exact outcome / repair control \\", r"\midrule"]
    for key, (unit, outcome) in descriptions.items():
        lines.append(" & ".join(esc(v) for v in (key, f"{studies[key]['finite_check_count']:,}", unit, outcome)) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", "}"]
    return ("\n".join(lines) + "\n").encode()


def build_figure(data):
    from reportlab.pdfgen.canvas import Canvas
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.lib.colors import HexColor
    font = Path("C:/Windows/Fonts/times.ttf")
    if font.exists():
        pdfmetrics.registerFont(TTFont("PaperSerif", str(font)))
        name = "PaperSerif"
    else:
        name = "Times-Roman"
    tables = {t["id"]: t for t in data["tables"]}
    rr = lambda key: [r["values"] for r in tables[key]["rows"]]
    out = io.BytesIO()
    c = Canvas(out, pagesize=(540, 184), invariant=1)
    c.setAuthor(""); c.setTitle("Observed local training costs")
    panels = []
    trees = tables["tree_timing_summary"]["rows"]
    tr = [(int(re.search(r"n(\d+)_", v["source_pointer"])[1]), v["values"]["training_wall_seconds/median"], v["values"]["training_wall_seconds/minimum"], v["values"]["training_wall_seconds/maximum"]) for v in trees]
    panels.append(("Trees: isolated repeats", "Training rows (thousands)", 400, 30, [("XGBoost", [(x / 1000, y, lo, hi) for x, y, lo, hi in tr])]))
    panels.append(("Images: hooks included", "Training images (thousands)", 22, 110,
        [(label, [(v["train_rows"] / 1000, v["train_seconds"], None, None) for v in rr("vision_scaling") if v["architecture"] == arch]) for arch, label in (("resnet50", "ResNet-50"), ("densenet121", "DenseNet-121"))]))
    panels.append(("LLMs: no gradient hooks", "Training rows (thousands)", 8.5, 550,
        [(label, [(v["training"]["rows"] / 1000, v["training"]["seconds"], None, None) for v in rr("llm_scaling") if v["model"] == arch]) for arch, label in (("gpt2", "GPT-2"), ("qwen2_5_0_5b", "Qwen-0.5B"))]))
    colors = [HexColor("#21577a"), HexColor("#a54821")]
    for i, (title, xlabel, xmax, ymax, series) in enumerate(panels):
        left, bottom, width, height = 33 + 180*i, 39, 137, 108
        c.setFillColorRGB(0,0,0); c.setFont(name, 10)
        c.drawCentredString(left + width/2, 172, title)
        c.setFont(name, 8)
        c.drawCentredString(left + width/2, 15, xlabel)
        c.saveState(); c.translate(left-23,bottom+height/2); c.rotate(90); c.drawCentredString(0,0,"Training seconds"); c.restoreState()
        for k in range(5):
            yy = bottom + height*k/4
            c.setStrokeColor(HexColor("#dddddd")); c.setLineWidth(.4); c.line(left,yy,left+width,yy)
            c.setFillColorRGB(0,0,0); c.drawRightString(left-3,yy-2, f"{ymax*k/4:g}")
        ticks = [50,200,400] if i==0 else ([2.7,10.8,21.6] if i==1 else [1.024,4.096,8.192])
        for x in ticks:
            xx=left+width*x/xmax
            c.drawCentredString(xx,bottom-12,f"{x:g}")
        c.setStrokeColorRGB(0,0,0); c.line(left,bottom,left+width,bottom); c.line(left,bottom,left,bottom+height)
        for j,(label,points) in enumerate(series):
            c.setStrokeColor(colors[j]); c.setFillColor(colors[j]); c.setLineWidth(1.1)
            points=sorted(points)
            for a,b in zip(points,points[1:]):
                c.line(left+width*a[0]/xmax,bottom+height*a[1]/ymax,left+width*b[0]/xmax,bottom+height*b[1]/ymax)
            for x,y,lo,hi in points:
                xx,yy=left+width*x/xmax,bottom+height*y/ymax
                if lo is not None:
                    yl,yh=bottom+height*lo/ymax,bottom+height*hi/ymax
                    c.line(xx,yl,xx,yh); c.line(xx-2,yl,xx+2,yl); c.line(xx-2,yh,xx+2,yh)
                if j==0: c.circle(xx,yy,2.2,fill=1,stroke=0)
                else: c.rect(xx-2,yy-2,4,4,fill=1,stroke=0)
            c.setFont(name,8); c.drawString(left+4,bottom+height-10-10*j,label)
    c.showPage(); c.save()
    return out.getvalue()


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check",action="store_true")
    args=p.parse_args()
    data=json.loads(DATA.read_text(encoding="utf-8"))
    gaps=json.loads((PAPER/"gap-construction-results.json").read_text(encoding="utf-8"))
    products={PAPER/"experimental-tables.tex":build_tex(data), PAPER/"figures/academic-scaling.pdf":build_figure(data), PAPER/"gap-tables.tex":build_gap_tex(gaps)}
    for path,payload in products.items():
        if args.check:
            if not path.exists() or path.read_bytes()!=payload:
                raise SystemExit(f"Generated artifact differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_bytes(payload)
    print(json.dumps({"status":"verified" if args.check else "generated", "artifacts":{str(path.relative_to(ROOT)):hashlib.sha256(value).hexdigest() for path,value in products.items()}}))


if __name__=="__main__":
    main()
