"""Production core for Model Release Assurance."""

from .engine import AssuranceEngine
from .incomplete_portfolio import (
    AnalyticPortfolioEvidenceEntry,
    CertificateVerification,
    ConditionalMarginalBounds,
    CouplingModel,
    EvidenceReference,
    IncompletePortfolioProblem,
    JointEventBound,
    RationalNumber,
    RationalUpperAudit,
    StatisticalCoverage,
    solve_analytic_portfolio,
    binary_uniform_diagonal_identified_bounds,
    decimal_fraction,
    outward_rounded_fraction,
    parity_interaction_identified_bounds,
    verify_analytic_portfolio,
    verify_portfolio_problem_evidence,
    verified_upper_fraction,
)
from .models import AssessmentRequest, AssessmentReport
from .optimizer import (
    OptimizationRequest,
    OptimizationReport,
    ReleaseOptimizer,
    SignedOptimizationManifest,
)
from .version import VERSION
from .portfolio_statistics import (
    AssuranceErrorBudget,
    IncompletePortfolioSpecification,
    MultinomialCountsFile,
    MultinomialEvidenceRequest,
    MultinomialSamplingPlan,
    SimultaneousMultinomialEvidence,
    compile_multinomial_portfolio_problem,
    generate_simultaneous_multinomial_evidence,
    verify_simultaneous_multinomial_evidence,
)
from .protocol_feasibility import (
    AuthorizationMode,
    ProtocolCertificateVerification,
    ProtocolFeasibilityCertificate,
    ProtocolFeasibilityProblem,
    ProtocolWorld,
    assurance_failure_upper_bound,
    maximal_sound_gate,
    solve_protocol_feasibility,
    robustly_releasable_configurations,
    verify_protocol_feasibility,
)

__all__ = [
    "AssuranceEngine",
    "AssessmentRequest",
    "AssessmentReport",
    "AnalyticPortfolioEvidenceEntry",
    "AssuranceErrorBudget",
    "CertificateVerification",
    "ConditionalMarginalBounds",
    "CouplingModel",
    "EvidenceReference",
    "IncompletePortfolioProblem",
    "IncompletePortfolioSpecification",
    "JointEventBound",
    "RationalNumber",
    "RationalUpperAudit",
    "OptimizationRequest",
    "OptimizationReport",
    "ReleaseOptimizer",
    "SignedOptimizationManifest",
    "StatisticalCoverage",
    "MultinomialCountsFile",
    "MultinomialEvidenceRequest",
    "MultinomialSamplingPlan",
    "SimultaneousMultinomialEvidence",
    "compile_multinomial_portfolio_problem",
    "generate_simultaneous_multinomial_evidence",
    "solve_analytic_portfolio",
    "binary_uniform_diagonal_identified_bounds",
    "decimal_fraction",
    "outward_rounded_fraction",
    "parity_interaction_identified_bounds",
    "verify_analytic_portfolio",
    "verify_portfolio_problem_evidence",
    "verified_upper_fraction",
    "verify_simultaneous_multinomial_evidence",
    "assurance_failure_upper_bound",
    "AuthorizationMode",
    "maximal_sound_gate",
    "ProtocolCertificateVerification",
    "ProtocolFeasibilityCertificate",
    "ProtocolFeasibilityProblem",
    "ProtocolWorld",
    "robustly_releasable_configurations",
    "solve_protocol_feasibility",
    "verify_protocol_feasibility",
]
__version__ = VERSION
