"""Governance Checker — model card generation, compliance report, checklist audit."""

from __future__ import annotations

from aisafety.core.base import BaseChecker
from aisafety.core.registry import register_checker
from aisafety.core.types import CheckResult, CheckStatus, Finding, SafetyReport, Severity

MODEL_CARD_TEMPLATE = """\
# Model Card: {name}

## Model Details
- **Name**: {name}
- **Version**: {version}
- **Type**: {model_type}
- **Description**: {description}

## Intended Use
{intended_use}

## Training Data
{training_data}

## Performance Metrics
{metrics}

## Limitations
{limitations}

## Ethical Considerations
{ethical_considerations}

## Safety Evaluation
{safety_summary}

---
Generated by AI Safety Checker v0.1.0
"""

NIST_RMF_CATEGORIES = {
    "confabulation": ["hallucination", "confabulation", "factual", "grounding"],
    "data_privacy": ["pii", "privacy", "membership_inference", "data_leak"],
    "information_integrity": ["toxicity", "bias", "fairness", "misinformation"],
    "toxic_content": ["toxicity", "harmful", "offensive", "hate"],
    "security": ["injection", "jailbreak", "adversarial", "prompt"],
    "human_ai_config": ["sycophancy", "refusal", "alignment", "agency"],
    "value_chain": ["tool_call", "supply_chain", "dependency"],
}

EU_AI_ACT_RISK = {
    "unacceptable": ["social_scoring", "real_time_biometric"],
    "high": ["hiring", "credit", "criminal_justice", "education", "healthcare"],
    "limited": ["chatbot", "deepfake", "emotion_recognition"],
    "minimal": ["spam_filter", "game_ai", "recommendation"],
}


@register_checker
class GovernanceChecker(BaseChecker):
    name = "Governance"
    category = "governance"
    requires = []

    def check(
        self,
        model_info: dict | None = None,
        safety_report: SafetyReport | None = None,
        framework: str = "nist",
        output_path: str | None = None,
        **kwargs,
    ) -> CheckResult:
        findings: list[Finding] = []

        if model_info is None:
            model_info = {}

        # Model card completeness
        findings.append(self._check_model_card_completeness(model_info))

        # Generate model card
        if output_path:
            self._generate_model_card(model_info, safety_report, output_path)
            findings.append(self._make_finding(
                "model_card_generated",
                "Model Card Generated",
                f"Model card written to {output_path}",
                Severity.INFO, CheckStatus.PASS,
            ))

        # Compliance mapping
        if safety_report:
            if framework == "nist":
                findings.extend(self._map_to_nist(safety_report))
            elif framework == "eu_ai_act":
                findings.extend(self._map_to_eu_ai_act(safety_report, model_info))

        # Checklist audit
        findings.append(self._checklist_audit(safety_report))

        return self._make_result(
            findings,
            metadata={"framework": framework, "model_name": model_info.get("name", "unknown")},
        )

    def _check_model_card_completeness(self, info: dict) -> Finding:
        required_fields = [
            "name", "version", "description", "intended_use",
            "training_data", "limitations", "ethical_considerations",
        ]
        present = [f for f in required_fields if info.get(f)]
        missing = [f for f in required_fields if not info.get(f)]

        completeness = len(present) / len(required_fields)

        if completeness < 0.5:
            severity, status = Severity.HIGH, CheckStatus.FAIL
        elif completeness < 0.8:
            severity, status = Severity.MEDIUM, CheckStatus.WARN
        else:
            severity, status = Severity.INFO, CheckStatus.PASS

        return self._make_finding(
            "model_card_completeness",
            "Model Card Completeness",
            f"{len(present)}/{len(required_fields)} required fields documented ({completeness:.0%})",
            severity, status,
            details={"present": present, "missing": missing, "completeness": completeness},
            recommendation=f"Document missing fields: {', '.join(missing)}" if missing else "",
        )

    def _generate_model_card(self, info: dict, report: SafetyReport | None, path: str) -> None:
        safety_summary = "No safety evaluation available."
        if report:
            s = report.summary
            safety_summary = (
                f"- Total checks: {s.total_checks}\n"
                f"- Passed: {s.passed}\n"
                f"- Failed: {s.failed}\n"
                f"- Warnings: {s.warnings}\n"
                f"- Critical findings: {s.critical_findings}\n"
                f"- Overall: **{s.overall_status.value.upper()}**"
            )

        def _fmt_metrics(metrics):
            if isinstance(metrics, dict):
                return "\n".join(f"- **{k}**: {v}" for k, v in metrics.items())
            return str(metrics) if metrics else "Not provided."

        card = MODEL_CARD_TEMPLATE.format(
            name=info.get("name", "Unknown Model"),
            version=info.get("version", "N/A"),
            model_type=info.get("model_type", "N/A"),
            description=info.get("description", "Not provided."),
            intended_use=info.get("intended_use", "Not provided."),
            training_data=info.get("training_data", "Not provided."),
            metrics=_fmt_metrics(info.get("metrics")),
            limitations=info.get("limitations", "Not provided."),
            ethical_considerations=info.get("ethical_considerations", "Not provided."),
            safety_summary=safety_summary,
        )

        with open(path, "w") as f:
            f.write(card)

    def _map_to_nist(self, report: SafetyReport) -> list[Finding]:
        """Map safety findings to NIST AI RMF risk categories."""
        category_coverage: dict[str, list[str]] = {cat: [] for cat in NIST_RMF_CATEGORIES}

        for result in report.results:
            for finding in result.findings:
                fid = finding.check_id.lower()
                for cat, keywords in NIST_RMF_CATEGORIES.items():
                    if any(kw in fid for kw in keywords):
                        status_label = f"{finding.check_id}: {finding.status.value}"
                        category_coverage[cat].append(status_label)

        covered = {k: v for k, v in category_coverage.items() if v}
        uncovered = {k for k, v in category_coverage.items() if not v}

        findings = []

        if uncovered:
            findings.append(self._make_finding(
                "nist_coverage",
                "NIST AI RMF Coverage",
                f"Covered {len(covered)}/{len(NIST_RMF_CATEGORIES)} risk categories. "
                f"Uncovered: {', '.join(uncovered)}",
                Severity.MEDIUM if len(uncovered) > 3 else Severity.LOW,
                CheckStatus.WARN if uncovered else CheckStatus.PASS,
                details={"covered": covered, "uncovered": list(uncovered)},
                recommendation="Add checks for uncovered NIST risk categories.",
            ))
        else:
            findings.append(self._make_finding(
                "nist_coverage",
                "NIST AI RMF Coverage",
                "All NIST AI RMF risk categories covered.",
                Severity.INFO, CheckStatus.PASS,
                details={"covered": covered},
            ))

        return findings

    def _map_to_eu_ai_act(self, report: SafetyReport, model_info: dict) -> list[Finding]:
        """Determine EU AI Act risk tier and compliance status."""
        intended_use = model_info.get("intended_use", "").lower()

        risk_tier = "minimal"
        for tier, keywords in EU_AI_ACT_RISK.items():
            if any(kw in intended_use for kw in keywords):
                risk_tier = tier
                break

        requirements = {
            "unacceptable": "This use case is prohibited under the EU AI Act.",
            "high": "Requires: conformity assessment, risk management, data governance, transparency, human oversight, accuracy/robustness testing.",
            "limited": "Requires: transparency obligations (users must be informed they are interacting with AI).",
            "minimal": "No mandatory requirements, but voluntary codes of practice recommended.",
        }

        if risk_tier == "unacceptable":
            severity, status = Severity.CRITICAL, CheckStatus.FAIL
        elif risk_tier == "high":
            severity = Severity.HIGH
            # Check if high-risk requirements are met by safety report
            has_fairness = any("fairness" in r.category for r in report.results)
            has_robustness = any("adversarial" in r.category for r in report.results)
            has_transparency = any("interpretability" in r.category for r in report.results)
            met = sum([has_fairness, has_robustness, has_transparency])
            status = CheckStatus.PASS if met >= 2 else CheckStatus.WARN
        else:
            severity, status = Severity.INFO, CheckStatus.PASS

        return [self._make_finding(
            "eu_ai_act",
            f"EU AI Act Classification: {risk_tier.upper()} Risk",
            requirements[risk_tier],
            severity, status,
            details={"risk_tier": risk_tier, "intended_use": model_info.get("intended_use", "")},
        )]

    def _checklist_audit(self, report: SafetyReport | None) -> Finding:
        """Compare findings against the safety checklist categories."""
        all_categories = [
            "data_safety", "adversarial", "fairness", "interpretability",
            "privacy", "alignment", "llm_prompt_safety", "llm_content_safety",
            "llm_guardrails", "agentic_safety", "governance",
        ]

        if report is None:
            return self._make_finding(
                "checklist_audit", "Checklist Coverage Audit",
                "No safety report provided — cannot audit checklist coverage.",
                Severity.MEDIUM, CheckStatus.SKIPPED,
            )

        covered = {r.category for r in report.results}
        uncovered = [c for c in all_categories if c not in covered]
        coverage = len(covered) / len(all_categories)

        if coverage < 0.5:
            severity, status = Severity.HIGH, CheckStatus.FAIL
        elif coverage < 0.8:
            severity, status = Severity.MEDIUM, CheckStatus.WARN
        else:
            severity, status = Severity.INFO, CheckStatus.PASS

        return self._make_finding(
            "checklist_coverage",
            "Safety Checklist Coverage",
            f"{len(covered)}/{len(all_categories)} categories checked ({coverage:.0%})",
            severity, status,
            details={"covered": list(covered), "uncovered": uncovered, "coverage": coverage},
            recommendation=f"Add checks for: {', '.join(uncovered)}" if uncovered else "",
        )
